name = "destru"
main = "build/worker/shim.mjs"
compatibility_date = "2025-03-23"

[build]
command = "cargo install -q worker-build && worker-build --release"

[observability]
enabled = true
head_sampling_rate = 1

[vars]
CLIENT_ID = "Iv23liftwY1oI5k4FzuF"
INSTALLATION_ID = "64597616"